config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'

  #static pages
  get	    '/about',		  to: 'static_pages#about'
  get	    '/features',	to: 'static_pages#features'
  get	    '/contact',		to: 'static_pages#contact'

=begin
  adds RESTful actions for Users resource and
  provides named routes for generating Users.user URLs
  
  int i >= 1

  HTTP REQUEST    URL             ACTION      NAMED ROUTE           PURPOSE
  GET             /users          index       users_path            page to list all users
  GET             /users/:id      show        users_path(user)      page to show user
  GET             /users/new      new         new_user_path         page to register new user
  POST            /users          create      users_path            create a new user
  GET             /users/:id/edit edit        edit_users_path(user) page to edit user where user.id = i
  PATCH           /users/:id      update      user_path(user)       update user
  DELETE          /users/:id      destroy     user_path(user)       delete user
=end
  resources :users do
    resources :transactions, :controller => 'transactions'
  end 

  get     '/register',  to: 'users#new'
  post    '/register',  to: 'users#create'
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  #get     'users/:user_id/portfolio', to: 'transactions#index'
  #match ':controller(/:action(/:user_id(.:format)))', :via => :all
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactions
  
  #callback to downcase email before saving to user.email
  before_save { self.email = email.downcase }
	
  #validate name input
  validates(
	:name, 
	presence: true, 
	length: { maximum: 50 })
	
  #validate email input
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
  validates(
	:email, 
	presence: true, 
	length: { maximum: 255 },
	format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }
	)
=begin
	secure password using BCRYPT
	includes: 
		method that allows ability to save securely hashed password_digest attribute to DB
		creation of virtual attributes password and password_confirmation
		authenticate method that returns user when password is correct
=end
  has_secure_password
	validates(
		:password,
		presence: true,
		length: { minimum: 6 }
		)

  #allows user fixture to be created with least-cost hashing
  def User.digest(string)
  	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
  	BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
require 'uri'
#require 'httparty'
require 'json'

class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
=begin 
	equivalent to:
	@user = User.new(name: "Foo Bar", email: "foo@bar.com",
					 password: "foobar", password_confirmation: "foobar")
=end
  	if @user.save
      log_in @user
  		flash[:success] = "Welcome to CoinLens!"
  		redirect_to @user 	#successful registration redirects user to profile
  	else
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])	#find method converts string 'id' into type int
  end

  #used to limit attributes submitted in params[:user] to only include table attributes
private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<% provide(:title, "Register") %>
<h1>Register</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user, url: register_path) do |f| %>
		<!--
		<form accept-charset="UTF-8" action="/users" class="new_user"
      	</i>d="new_user" method="post">
      	-->
		  <%=render 'shared/error_messages' %>
		  <%= f.label :name %>
		  <%= f.text_field :name, class: 'form-control' %>
		  <!-- 
		  Embedded Ruby produces following code:
		  <label for="user_name">Name</label>
		  <input id="user_name" name=user[name]" type="text" />
		  -->

		  <%= f.label :email %>
		  <%= f.email_field :email, class: 'form-control' %>

		  <%= f.label :password %>
		  <%= f.password_field :password, class: 'form-control' %>

		  <%= f.label :password_confirmation, "Confirm Password" %>
		  <%= f.password_field :password_confirmation, class: 'form-control' %>

		  <%= f.submit "Create my account", class: "btn btn-primary" %>
		  <!--
		  <input class="btn btn-primary" name="commit" type="submit" value="Create my account" />
		  -->
		<% end %>
		<!-- </form> -->
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>Dashboard</h1>
	<p id="navigate-dash">
		<center><%= link_to "Go to your portfolio", user_transactions_path(@user) %></center>
	</p>