config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'

  #static pages
  get	    '/about',		  to: 'static_pages#about'
  get	    '/features',	to: 'static_pages#features'
  get	    '/contact',		to: 'static_pages#contact'

=begin
  adds RESTful actions for Users resource and
  provides named routes for generating Users.user URLs
  
  int i >= 1

  HTTP REQUEST    URL             ACTION      NAMED ROUTE           PURPOSE
  GET             /users          index       users_path            page to list all users
  GET             /users/:id      show        users_path(user)      page to show user
  GET             /users/new      new         new_user_path         page to register new user
  POST            /users          create      users_path            create a new user
  GET             /users/:id/edit edit        edit_users_path(user) page to edit user where user.id = i
  PATCH           /users/:id      update      user_path(user)       update user
  DELETE          /users/:id      destroy     user_path(user)       delete user
=end
  resources :users do
    resources :transactions, :controller => 'transactions'
  end 

  get     '/register',  to: 'users#new'
  post    '/register',  to: 'users#create'
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  #get     'users/:user_id/portfolio', to: 'transactions#index'
  #match ':controller(/:action(/:user_id(.:format)))', :via => :all
end

app/controllers/transactions_controller.rb
require 'httparty'
require 'time'
require 'uri'

class TransactionsController < ApplicationController
  before_action :setevent
  
  def setevent
  	@user = User.find(params[:user_id])
    @api_link = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest'
  end

  # REST Api call
  def pullApi(symbol)
    response = HTTParty.get(
      @api_link,
      :query => {'symbol' => symbol}, 
      :headers => {'X-CMC_PRO_API_KEY' => ENV["CMC_API_KEY"], 'Content-Type' => 'application/json'}
    )
  end

  def index
  	@total = 0
  	@transactions = @user.transactions
  	@txarray = Array.new
  	@transactions.each do |t|
  		coin_name = Coin.find(t.coin_id).name
  		symbol = Coin.find(t.coin_id).symbol
  		data = pullApi(symbol)
  		price = data['data'][symbol]['quote']['USD']['price']
  		value = price.to_f * t.amount
  		@total = @total + value
  		transaction_arr = [coin_name, value]
  		@txarray.push(transaction_arr)
  	end
  	@rounded_total = @total.round(2)
  end

  def new
  	@coins = Coin.order(:name)
  	@transaction = @user.transactions.build
  end

  def create
  	@transaction = @user.transactions.new(transaction_params)

  	if @transaction.save
  		flash[:success] = "Successfully added to your portfolio."
  		redirect_to :action => :index
  	else
  		render 'new'
  	end
  end

  def show
  	transaction = @user.transactions.find(params[:id])
  	@coin_name = Coin.find(transaction.coin_id).name
  	@coin_symbol = Coin.find(transaction.coin_id).symbol
    @data = pullApi(@coin_symbol)
  	@rank = @data['data'][@coin_symbol]['cmc_rank']
  	@price = @data['data'][@coin_symbol]['quote']['USD']['price'].to_f.round(2)
  	@day_change = @data['data'][@coin_symbol]['quote']['USD']["percent_change_24h"]
  	@curr_holding = transaction.amount
  	@value = (@price * @curr_holding).round(2)

  	day_chart_api = "https://min-api.cryptocompare.com/data/histoday?fsym=#{@coin_symbol}&tsym=USD&limit=7"
  	@day_response = HTTParty.get(day_chart_api,
    		   		:headers =>{'Content-Type' => 'application/json'})
  	@histoday_arr = Array.new
  	(0..7).each do |i|
  			date = Time.at(@day_response["Data"][i]["time"]).strftime("%Y-%m-%d")
  			close = @day_response["Data"][i]["close"]
  			date_arr = [date,close]
  			@histoday_arr.push(date_arr)
  	end
	
  	hour_chart_api = "https://min-api.cryptocompare.com/data/histohour?fsym=#{@coin_symbol}&tsym=USD&limit=10"
  	@hour_response = HTTParty.get(hour_chart_api,
    		   		 :headers =>{'Content-Type' => 'application/json'})
  	@histohour_arr = Array.new
  	(0..10).each do |i|
  		date = Time.at(@hour_response["Data"][i]["time"]).strftime("%c")
  		close = @hour_response["Data"][i]["close"]
  		date_arr = [date,close]
  		@histohour_arr.push(date_arr)
  	end
  end


  def edit
  	@transaction = @user.transactions.find(params[:id])
  end

  def update
  	@transaction = @user.transactions.find(params[:id])

  	if @transaction.update(transaction_params)
  		flash[:success] = "Successfully updated your portfolio."
  		redirect_to :action => :index
  	else
  		flash.now[:danger] = "Amount cannot be blank."
  		render :action => :new
  	end
  end

  def destroy
  	@transaction = @user.transactions.find(params[:id])
  	if @transaction.destroy
  		flash[:success] = "Successfully removed from your portfolio."
  	end
  	redirect_to :action => :index
  end

 private
  	def transaction_params
  		params.require(:transaction).permit(:user_id, :coin_id, :amount)
  	end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/edit.html.erb
<% provide(:title, "Edit Holding") %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @transaction, :url => { :controller => 'transactions', :action => 'update', :id => @transaction} do |f| %>
    		<%= f.label :amount, "Amount" %>
    		<%= f.text_area :amount %>
    		<%= f.submit "Update" %>
		<% end %>
	</div>
</div>

app/views/transactions/index.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<% provide(:title, "Portfolio") %>
<meta name="viewport" content="width=device-width, initial-scale=1">
	<h1><b>Current Holdings</b></h1>
	<div class = "row">
		<div class="column side1">
			<div align="left">
				<%= link_to 'New Coin', new_user_transaction_path, :class => "btn btn-primary"%> 
			</div>
			<br>
				<ul id="coin-list">
					<table class='table'>
						<% @transactions.each do |t| %>
							<tr>
								<td>
									<b><%= Coin.find(t.coin_id).name %></b>
								</td>
								<td>
									<%= link_to 'Show', user_transaction_path(@user, t), :class => "btn btn-primary"%>
									<%= link_to 'Edit', edit_user_transaction_path(@user, t), :class => "btn btn-warning"%>
									<%= link_to 'Delete', user_transaction_path(@user, t), :method => :delete,:class => "btn btn-danger" %>
								</td>
							</tr>
						<%end%>
					</table>
				</ul>
		</div>
		<div class="column middle1 text-center">
			<%= pie_chart @txarray , donut:true%>
			<b><p>Total: $<%=@rounded_total%></b></p>
		</div>
	</div>

	

app/views/transactions/new.html.erb
<% provide(:title, "Add Coin") %>
<h1>Add a holding</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @transaction, :url => { :controller => 'transactions', :action => 'create' } do |f| %>
    	<%= f.label :name, "Name" %>
    	<%= f.hidden_field :user_id, value: @current_user %>
    	<%= f.select :coin_id, options_from_collection_for_select(@coins, "id", "name") %>

   		<%= f.label :amount, "Amount" %>
    	<%= f.text_area :amount %>

    	<%= f.submit "Add to portfolio" %>
		<% end %>
	</div>
</div>

app/views/transactions/show.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<% provide(:title, @coin_name) %>

<div class="header">
	<h1><%= @coin_name %> (<%= @coin_symbol %>)</h1>
	<center><h7><%= link_to 'Back to Portfolio', :controller => 'transactions', :action => 'index' %></h7></center>
</div>

<div class="row">
	<div class="column side">
		<ul id="coin-info">
			<li>Rank: <%= @rank %></li>
			<li>Price (USD): <%= @price %></li>
			<li>24H Change: <%= @day_change %>%</li>
			<li>Current holdings: <%= @curr_holding %></li>
			<li>Total value: <%= @value %></li>
		</ul>
		
		<style>
			div.tab-content{
				width = 100%
			}
		</style>
	</div>
	
	<div class="column middle">
		<div class="container">
			<ul class="nav nav-tabs nav-justified">
				<li class="active"><a data-toggle="tab" href="#Weekly">Weekly</a></li>
				<li><a data-toggle="tab" href="#Hourly">Hourly</a></li>
			</ul>

			<div class="tab-content">
				<div id="Weekly" class = "tab-pane fade in active">
					<%= line_chart @histoday_arr, width: "1200px", height: "800px" %>
				</div>
				<div id="Hourly" class = "tab-pane fade in active">
					<%= line_chart @histohour_arr, width: "1200px", height: "800px"%>
				</div>
			</div>
		</div>
	</div>
</div>