config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'

  #static pages
  get	    '/about',		  to: 'static_pages#about'
  get	    '/features',	to: 'static_pages#features'
  get	    '/contact',		to: 'static_pages#contact'

=begin
  adds RESTful actions for Users resource and
  provides named routes for generating Users.user URLs
  
  int i >= 1

  HTTP REQUEST    URL             ACTION      NAMED ROUTE           PURPOSE
  GET             /users          index       users_path            page to list all users
  GET             /users/:id      show        users_path(user)      page to show user
  GET             /users/new      new         new_user_path         page to register new user
  POST            /users          create      users_path            create a new user
  GET             /users/:id/edit edit        edit_users_path(user) page to edit user where user.id = i
  PATCH           /users/:id      update      user_path(user)       update user
  DELETE          /users/:id      destroy     user_path(user)       delete user
=end
  resources :users do
    resources :transactions, :controller => 'transactions'
  end 

  get     '/register',  to: 'users#new'
  post    '/register',  to: 'users#create'
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  #get     'users/:user_id/portfolio', to: 'transactions#index'
  #match ':controller(/:action(/:user_id(.:format)))', :via => :all
end

app/views/layouts/_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://github.com/zf-jiang/coinlens">Github</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "CoinLens", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   root_path %></li>
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Register", register_path %></li>
            <li><%= link_to "Login",   login_path %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- Legacy support for browsers that do no support HTML5. -->
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="welcomemsg">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      </div>
      <%= yield %>
      <%= render 'layouts/footer' %>

      <!-- Restrict debugging information to ONLY development environment -->
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>
<p style="color: green"><%= flash[:notice] %></p>